---
title: "Assignment 1: Introduction"
author: "Humayra Rahman"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: ___

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I worked with R during an undergrad class, but never with Git.

2. Are there any components of the course about which you feel confident?

> Answer: I am still learning.

3. Are there any components of the course about which you feel apprehensive?

> Answer: Most of the components as of now. I am anxious about making little silly mistakes that lead to more complex ones.

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: I mostly worked with secondary datasets in my past roles.

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: Ordinal data because it has a clear order.

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/hum-r/EDE_Spring2026

---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
